MIPS: fix wrong vfork aliases in libpthread.so
This is a backport from trunk:
43c2948756bb6e144c7b871e827bba37d61ad3a3
b87c1ec3fa398646f042a68f0ce0f7d09c1348c7

With recent binutils versions the GNU libc fails to build on at least
MIPS and SPARC, with this kind of error:

  /home/aurel32/glibc/glibc-build/nptl/libpthread.so:(*IND*+0x0): multiple definition of `vfork@GLIBC_2.0'
  /home/aurel32/glibc/glibc-build/nptl/libpthread.so::(.text+0xee50): first defined here

It appears that on these architectures pt-vfork.S includes vfork.S
(through the alpha version of pt-vfork.S) and that the __vfork aliases
are not conditionalized on IS_IN (libc) like on other architectures.
Therefore the aliases are also wrongly included in libpthread.so.

Fix this by properly conditionalizing the aliases like on other
architectures.